version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/src/infra/infra_php/"
    schedule:
      interval: "daily"
